# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/form.ui'
#
# Created: Sat Mar 23 12:49:00 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(797, 801)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButtonRefDSPattern = QtGui.QPushButton(self.centralwidget)
        self.pushButtonRefDSPattern.setGeometry(QtCore.QRect(270, 20, 211, 27))
        self.pushButtonRefDSPattern.setObjectName(_fromUtf8("pushButtonRefDSPattern"))
        self.lineEditRefDsPattern = QtGui.QLineEdit(self.centralwidget)
        self.lineEditRefDsPattern.setGeometry(QtCore.QRect(10, 20, 241, 25))
        self.lineEditRefDsPattern.setText(_fromUtf8(""))
        self.lineEditRefDsPattern.setObjectName(_fromUtf8("lineEditRefDsPattern"))
        self.comboBoxRefDS = QtGui.QComboBox(self.centralwidget)
        self.comboBoxRefDS.setGeometry(QtCore.QRect(10, 70, 471, 25))
        self.comboBoxRefDS.setObjectName(_fromUtf8("comboBoxRefDS"))
        self.lineEditRemainingDSsPattern = QtGui.QLineEdit(self.centralwidget)
        self.lineEditRemainingDSsPattern.setGeometry(QtCore.QRect(10, 190, 241, 25))
        self.lineEditRemainingDSsPattern.setText(_fromUtf8(""))
        self.lineEditRemainingDSsPattern.setObjectName(_fromUtf8("lineEditRemainingDSsPattern"))
        self.pushButtonRemainingDSsPattern = QtGui.QPushButton(self.centralwidget)
        self.pushButtonRemainingDSsPattern.setGeometry(QtCore.QRect(270, 190, 191, 27))
        self.pushButtonRemainingDSsPattern.setObjectName(_fromUtf8("pushButtonRemainingDSsPattern"))
        self.table = QtGui.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 230, 771, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setObjectName(_fromUtf8("table"))
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table.setHorizontalHeaderItem(2, item)
        self.pushButtonCellDetails = QtGui.QPushButton(self.centralwidget)
        self.pushButtonCellDetails.setGeometry(QtCore.QRect(490, 70, 111, 27))
        self.pushButtonCellDetails.setObjectName(_fromUtf8("pushButtonCellDetails"))
        self.lineEditUnitCell = QtGui.QLineEdit(self.centralwidget)
        self.lineEditUnitCell.setGeometry(QtCore.QRect(110, 140, 341, 25))
        self.lineEditUnitCell.setObjectName(_fromUtf8("lineEditUnitCell"))
        self.lineEditSpaceGroup = QtGui.QLineEdit(self.centralwidget)
        self.lineEditSpaceGroup.setGeometry(QtCore.QRect(10, 140, 81, 25))
        self.lineEditSpaceGroup.setObjectName(_fromUtf8("lineEditSpaceGroup"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 120, 161, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButtonProcessRefDS = QtGui.QPushButton(self.centralwidget)
        self.pushButtonProcessRefDS.setGeometry(QtCore.QRect(600, 130, 161, 27))
        self.pushButtonProcessRefDS.setObjectName(_fromUtf8("pushButtonProcessRefDS"))
        self.pushButtonProcessAllDS = QtGui.QPushButton(self.centralwidget)
        self.pushButtonProcessAllDS.setGeometry(QtCore.QRect(380, 450, 191, 27))
        self.pushButtonProcessAllDS.setObjectName(_fromUtf8("pushButtonProcessAllDS"))
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 490, 771, 251))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.lineEditResolution = QtGui.QLineEdit(self.centralwidget)
        self.lineEditResolution.setGeometry(QtCore.QRect(290, 450, 71, 21))
        self.lineEditResolution.setText(_fromUtf8(""))
        self.lineEditResolution.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditResolution.setObjectName(_fromUtf8("lineEditResolution"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 450, 111, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 120, 131, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.radioButtonFriedelTrue = QtGui.QRadioButton(self.centralwidget)
        self.radioButtonFriedelTrue.setGeometry(QtCore.QRect(460, 140, 102, 20))
        self.radioButtonFriedelTrue.setChecked(True)
        self.radioButtonFriedelTrue.setObjectName(_fromUtf8("radioButtonFriedelTrue"))
        self.radioButtonFriedelFalse = QtGui.QRadioButton(self.centralwidget)
        self.radioButtonFriedelFalse.setGeometry(QtCore.QRect(520, 140, 102, 20))
        self.radioButtonFriedelFalse.setObjectName(_fromUtf8("radioButtonFriedelFalse"))
        self.checkBoxNedit = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxNedit.setGeometry(QtCore.QRect(10, 450, 191, 22))
        self.checkBoxNedit.setObjectName(_fromUtf8("checkBoxNedit"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 50, 771, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 100, 771, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 170, 771, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.comboBoxRefDS, QtCore.SIGNAL(_fromUtf8("activated(QString)")), self.statusbar.showMessage)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRefDSPattern.setText(QtGui.QApplication.translate("MainWindow", "Get Reference Data set", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRemainingDSsPattern.setText(QtGui.QApplication.translate("MainWindow", "Get  Remaining Data sets", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Data Set", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Process in XDS", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Include in XSCALE", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCellDetails.setText(QtGui.QApplication.translate("MainWindow", "Get Cell details", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Space Group", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Unit Cell Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonProcessRefDS.setText(QtGui.QApplication.translate("MainWindow", "Process Ref Data set", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonProcessAllDS.setText(QtGui.QApplication.translate("MainWindow", "Process all Data sets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Resolution up to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Friedel\'s law", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonFriedelTrue.setText(QtGui.QApplication.translate("MainWindow", "True", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonFriedelFalse.setText(QtGui.QApplication.translate("MainWindow", "False", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxNedit.setText(QtGui.QApplication.translate("MainWindow", "Edit XSCALE.INP?", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

